import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Providers from "./providers";
import Sidebar from "@/components/layout/Sidebar";
import Header from "@/components/layout/Header";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#121212] text-white overflow-hidden`}
      >
        <Providers>
          <div className="flex h-screen w-full">
            <Sidebar />
            <div className="flex-1 flex flex-col ml-64 overflow-hidden">
              <Header />
              <main className="flex-1 overflow-y-auto p-8 bg-[#121212]">
                {children}
              </main>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}

